= AngularJS basics
some basic ideas, presentation chunks

++++
<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.1.0/css/font-awesome.min.css">
++++

:icons: font

== Overview

angularjs - *single page applications*, structural framework for dynamic apps

It's all about data binding - most basic and impressive feature +
HTML becomes a *live template* that depicts the background javascript model +
The *ng-app* directive says that everything inside is and ng application and should become this live template

[source,html]
<html ng-app>

Any time the model is changed in the client-side model, the view reflects these changes without writing any custom code. *It just works*
 
TIP: This process is dirty checking. Dirty checking is a relatively efficient approach to checking for
changes on a model. Every time there could be a potential change, Angular will do a dirty check
inside its event loop (discussed in depth in the under the hood chapter) to ensure everything is
consistent.

*ng* uses HTML5 power to say *how the data should be displayed*

On the other side the *javascript model* in the background *is always in sync* because the binding is *bi-directional*

TIP: Bi-directional in this context means that if the view changes the value, the model
observes the change through dirty checking, and if the model changes the value, the
view update with the change.

=== DOM to model binding
The code in `{{ }}` is called an *expression* - it is *evaluated* if it's a part on an ng-app
[source,html]
<input ng-model="person.name" type="text" placeholder="Your name">
<h1>Hello {{ person.name }}</h1>
